apiVersion: v1
kind: Service
metadata:
  name: wayshub-frontend  
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: wayshub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayshub-frontend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wayshub"
      #deployment: "true"
  template:
    metadata:
      labels:
        app: "wayshub"
        #deployment: "true"
    spec:
      containers:
      - name: wayshub-frontend
        image: ilhaskam/wayshub-frontend-kubernetes:v1
        ports:
        - containerPort: 3000
        env:
        - name: TITLE
          value: "Wayshub Demo"
