#apiVersion: v1
#kind: Pod
#metadata:
  #name: aks-with-node-affinity
#spec:
  #affinity:
    #nodeAffinity:
      #requiredDuringSchedulingIgnoredDuringExecution:
        #nodeSelectorTerms:
        #- matchExpressions:
          #- key: topology.kubernetes.io/zone
            #operator: In
            #values:
            #- asia-southeast1-a
      #preferredDuringSchedulingIgnoredDuringExecution:
      #- weight: 1
        #preference:
          #matchExpressions:
          #- key: app
            #operator: In
            #values:
            #- aks
  #nodeSelector:
    #app: aks
  #containers:
    #- name: aks-with-node-affinity
      #image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
      #ports:
        #- containerPort: 80
#---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservice-aks
  annotations:
    # kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production-aks
spec:
  rules:
  - host: aks.studentdumbways.my.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aks
            port:
              number: 80
  ingressClassName: nginx
  tls:
    - hosts:
        - aks.studentdumbways.my.id
      secretName: ssl-aks
---
apiVersion: v1
kind: Service
metadata:
  name: aks 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks
  template:
    metadata:
      labels:
        app: aks
    spec:
      containers:
      - name: aks
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "AKS Ingress Demo"
      #nodeSelector:
        #app: aks
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-aks
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ilhaskam@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-aks
    solvers:
      - http01:
          ingress:
            class: nginx
